- marauder/lib/marauder/commands.rb
This allows you to get the IP address, AMI or other field instead of dnsName if it is more appropriate. Particularly useful if you are working on hosts in a VPC for which DNS resolution is unavailable.
> Add support to prism to output a particular field

- app/agent/origin.scala
- app/collectors/instance.scala
- app/conf/context.scala
This is to help with the migration of flexible content into AWS (by preventing riff-raff trying to deploy to servers in AWS)
> Add ability to prefix values to stages in AWS

- marauder/lib/marauder/commands.rb
- marauder/lib/marauder/marauder.rb
I'm working on a larger update to Prism to migrate it into AWS. As part of this the `hardware` endpoint is being removed so this is an update to marauder to deal with the resulting 404.
At the same time I've added a longed for change to detect if there is no public address on an instance  and return the IP instead. This is really useful for working with instances inside VPCs.
I'm bumping the version to 0.7.0 due to the fact that this is essentially deprecating the hardware endpoint.
> Couple of marauder updates to go with the Prism migration

- marauder/README.md
`r2frontend QA` is no more, so updated example.
> Update example (R2 QA is no more!)

- app/agent/collector.scala
- app/agent/origin.scala
- app/collectors/image.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- conf/routes
Add the crawling and exploration of AMIs to Prism.
This logic only crawls image data for those images which are owned by the account being crawled. This means that images provided by third parties such as ubuntu will not be indexed.
> Add image crawling and endpoints

- app/agent/origin.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/securityGroup.scala
- app/conf/context.scala
During the hack week I overloaded the existing config in an ugly way to pull in AMIs owned by other accounts. That approach produced misleading account numbers amongst other things - so this untangles the overloading somewhat.
> Separate config for indexing AMIs from normal accounts.

- app/collectors/image.scala
We don't much care for kernel or ramdisk images, so let's ignore them. This also adds a couple of new fields that we probably do care about.
> Filter for machine images up front.

- app/collectors/launchConfigurations.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- build.sbt
- cloudformation/prism-role.template
- cloudformation/prism-user.template
- conf/routes
This adds launch configurations to the list of items that Prism indexes from each account.
Sadly prism doesn't have permission to call this at present so we must update the cloudformation in each account.
> Add launch configurations to the the items Prism indexes

- app/PrismApplicationLoader.scala
The Prism build has been failing since TeamCity was moved to AWS. This was because it was assuming that the tests would be run in a non-AWS environment and this was no longer true.
I've changed the code to check the mode of the play application.
> Fix tests when run in AWS

- app/collectors/bucket.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- build.sbt
- cloudformation/prism-role.template
- cloudformation/prism-user.template
- conf/routes
This adds s3 buckets to the list of items that Prism indexes from each account.
Sadly prism doesn't have permission to call this at present so we must update the cloudformation in each account.
Added a commit to update to scala `2.11.8` as well.
Fixes #33 
@sihil
> Add s3 buckets to the the items Prism indexes

- app/collectors/instance.scala
- app/collectors/reservation.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- conf/routes
This adds reservation information to the list of items that Prism indexes from each account.
I plan to use this data and the `/instances` endpoint to make decisions on reservations / on-demand for tools accounts.
> Fetch and list reservation information.

- app/PrismApplicationLoader.scala
- app/agent/origin.scala
- app/collectors/acmCertificates.scala
- app/collectors/bucket.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/launchConfigurations.scala
- app/collectors/reservation.scala
- app/collectors/securityGroup.scala
- app/collectors/serverCertificates.scala
- app/conf/AWS.scala
- app/conf/DynamoConfiguration.scala
- app/conf/context.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- build.sbt
- conf/routes
Expiring ACM certificates are becoming a problem to it makes sense to have a way of easily identifying certificates that are close to expiring. Adding an endpoint to prism makes this somewhat easier to do at a departmental level.
The new collector needs a couple of new permissions. This has been added to the Prism role CFN template over at https://github.com/guardian/deploy-tools-platform/pull/61. This needs to be merged / rolled out to all of the accounts before this can be deployed.
TODO:
> Add ACM certificates endpoint to Prism

- app/collectors/acmCertificates.scala
- app/controllers/Api.scala
In the real world it seems that `getValidationEmails` can return `null`. This wraps it in `Option` and massages it appropriately.
I've also changed acm-certificates to acmCertificates as it makes jq wrangling easier.
> Deal with null from getValidationEmails

- app/agent/origin.scala
- app/conf/context.scala
Rather than trying to [retrofit](https://github.com/guardian/prism/pull/49) the account owner in the Owner endpoint, following a conversation with @sihil this is another approach where I insert the owner of the account at the Origin level.
The optional property is named `ownerId` and contains the first half of our emails addresses. It's optional as it doesn't make sense to set it for amis origins, as they're external to our department.
The property is read from the configuration, and falls back to a default, there again read from the configuration. I didn't hard-code a default mailing list to avoid pushing that publicly, we'll just have to ensure the property is present in the config.
It looks like that: 
```json
origin": {
"accountName": "someAccount",
"ownerId": "some.email.handle", …
```
> Add account owners to the origin object

- app/data/Owners.scala
- build.sbt
The AMIable weekly e-mails are working well so this fleshes out the ownership list so that it covers more of the known SSA combinations.
I also change the default recipient to be the tooling e-mail list so it's not just @philwills that is bombarded with them.
> Add more detailed ownership for stacks

- app/collectors/launchConfigurations.scala
In theory this should be useful for ease of auditing, but in practice there are sometimes credentials in userdata. As such making it so easy to access is a security concern.
> Don't store or publish userdata

- app/data/Owners.scala
We're removing all traces of `tailor` from our estate and have followed
this thread to: https://prism.gutools.co.uk/owners.
> Remove `tailor`

- app/data/Owners.scala
So that we receive notifications to the correct email address if we are running out of date AMIs.
> Update contact for Reader Revenue stacks

- app/collectors/data.scala
- app/controllers/Api.scala
Stack in Riff-Raff is mandatory but Prism wasn't enforcing this with the data it used. This modifies it such that stack is mandatory in Prism too.
The underlying data has been modified to be correct.
> Stack is now mandatory

- app/agent/collector.scala
- app/agent/model.scala
- app/collectors/acmCertificates.scala
- app/collectors/bucket.scala
- app/collectors/data.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/launchConfigurations.scala
- app/collectors/loadBalancers.scala
- app/collectors/reservation.scala
- app/collectors/securityGroup.scala
- app/collectors/serverCertificates.scala
- app/collectors/zone.scala
- app/controllers/Api.scala
- app/controllers/ApiResult.scala
- app/controllers/OwnerApi.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- app/utils/PaginatedAWSRequest.scala
- build.sbt
- conf/routes
- test/CollectorModelSpec.scala
This adds crawling of Route53 hosted zones (including records) and also elastic load balancers.
As part of this the AWS libraries are bumped and a paginator is introduced. Note that instances were not previously paged in Prism and so some instances may not have been correctly crawled in the past (although there is scant evidence that any account was impacted by this). This fixes that.
TODO
------
> Add Route53

- app/data/Owners.scala
We no longer have any resources with this stack (I've double checked), so removing it.
> Remove non-existent ELK stack from owners

- build.sbt
- project/build.properties
- riff-raff.yaml
We're currently using an insecure version of the AWS SDK, and a rather old version of sbt. This PR should hopefully solve that.
> Bump sbt version and aws sdk.

- marauder/README.md
Not really any security implications I can think of since we already quote the URL a few lines above.
> Fix prism-url

- app/data/Owners.scala
pfi-giant and pfi-playground did not have any owners, this pr adds the digital investigations as the owners.
> Digital investigations owns pfi stacks

- app/agent/collector.scala
- app/agent/model.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/conf/context.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- app/utils/PaginatedAWSRequest.scala
- build.sbt
- conf/routes
For example... 
... this particular one is filtered on `runtime`, which is a nice touch and will help with Node EOL upgrades.
Original motivation here was actually to ensure `Stage`s used for lambdas were available in RiffRaff - for example in RR we use `DEV` Stage for quite a number of API Gateway backed lambdas (for consistency with play apps where the `DEV` instance runs on our machines - but that's much harder for API Gateway Lambdas).
- `lambda:ListFunctions`
- `lambda:ListTags`
... see https://github.com/guardian/deploy-tools-platform/pull/181 (will be StackSet to all the AWD accounts).
> add lambda indexing

- app/controllers/Api.scala
This makes all data keys consistently kebab-case instead of camelCase. This lines up with the endpoint URIs and helps make it easier to make a generic tool to consume the data.
> Make the key names consistent with the routes

- app/collectors/acmCertificates.scala
- app/jsonimplicits/implicits.scala
- build.sbt
Data about whether an ACM certificate was DNS or EMAIL validated wasn't available in Prism but would be super useful.
> Add DNS validation info to ACM certificates

- app/collectors/acmCertificates.scala
Now we have a service that is carrying out validations every minute we should decrease the polling interval to match.
> Decrease ACM polling inteval to 1 minute

- app/collectors/bucket.scala
Two issues here
- buckets are a global service so we need to filter them appropriately into the "owned" regions
- if we are crawling `us-east-1` and we look at a bucket from another region all hell breaks loose: see https://github.com/aws/aws-sdk-java/issues/1338
Tested in CODE (with Prism configured to crawl `us-east-1` in addition to `eu-west-1`).
> Deal with buckets being collected from multiple regions

- app/data/Owners.scala
Remove email address associated with individual and replace it with a group email.
@adamnfish does not escape as I have added him to the group anyway. /sorry
More than one person receives AMIable alerts for outdated AMIs in the security stack 😁
> Switch to group email for security SAA

- app/collectors/acmCertificates.scala
A `FAILED` cert in multimedia was causing this code path to explode and therefore causing a failed schedule deploy of Prism. This has been tested locally and also will be in CODE shortly.
Successful deploy into CODE.
> Deal with null list of validation options

- scripts/ci
Here we add a CI script for the `riffRaffNotifyTeamcity` task, so we can change teamcity's build runner from the SBT plugin to the Command Line. 
We decided to do this, because when building PR #84 the build failed with an ominous error: `java.lang.NoClassDefFoundError: sbt/TrackLevel`. We thought that if we could forego teamcity's use of the SBT plugin, we might solve the problem.
https://teamcity.gutools.co.uk/buildConfiguration/Tools_Prism/580727?showLog=580727_217_42.217
We're going to test by: 
1. changing the teamcity config to use the command line build runner and then,
1. merging this PR into Prism's main branch to see if teamcity can build it. If that's successful, we will
1. rebase PR #84 on top of master
https://teamcity.gutools.co.uk/admin/editRunType.html?id=buildType:Tools_Pr …
> Add CI script for riffRaffNotifyTeamcity task 

- app/AppLoader.scala
- app/agent/origin.scala
- app/utils/AWSCredentialProviders.scala
Currently in DEV we need numerous AWS credentials:
- a set for the default profile
- a set for each profile defined in config
If we do not have one of these credentials, we get are greeted with an exception from the AWS SDK. The exception is fairly descriptive `The security token included in the request is expired`, however it's not clear which set of credentials are not valid.
This change adds a log line in an attempt to make it easier to understand which credentials are not valid. That is, the logs will look something like below, where the profile is echoed next to the Exception.
🚨 This change also moves to using the `deployTools` profile rather than the `default` profile when fetching config from DynamoDb. This is more inline with our other apps.
```
2020-10-27 13:31:12,474 …
```
> log which AWS profile is used to aid debugging

- app/AppLoader.scala
- app/conf/LogConfiguration.scala
- build.sbt
Let's enable prism to log to central ELK! Once this PR is merged, we will test by deploying to CODE and will add screenshots here.
An additional piece of work will be to double check all the log lines in prism and make sure we're happy sending them to central ELK.
Cloudformation changes are here: https://github.com/guardian/deploy-tools-platform/pull/249
> Ship logs to central ELK

- app/agent/collector.scala
- app/agent/model.scala
- app/agent/origin.scala
- app/controllers/ApiResult.scala
- app/controllers/OwnerApi.scala
- app/utils/Marker.scala
- test/ApiSpec.scala
We're currently working on PR #88, which allows prism to crawl all the AWS regions available to it. This work is facing a problem in that prism is unable to pass the loadbalancer health check when trying to crawl 13 or more regions. This means that we can't deploy this work! 
In order to help us better understand this problem we have started shipping prism logs to central ELK (PR #90). In particular we're interested to know how long exactly prism takes to pass its healthcheck. 
This PR introduces Markers so that we can analyse the time taken for prism to crawl certain resources and regions. We're hoping to use the graphing features of Kibana to help us analyse this data. 
Here are the markers that we've introduced:
- resource -> this is the name of the resource eg lambda
- account -> the …
> adds markers to aid debugging of healthcheck fails

- app/AppComponents.scala
- app/agent/collector.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
The root problem we're trying to solve is to have visibility over which AWS resources we have employed across the Guardian estate. Currently we don't have that, which is a security concern. So PR #88 aims to solve this by making Prism crawl all the 16 AWS regions that it has access to. 
In order to deploy this feature, we need Prism to pass its healthcheck, which it is currently only doing with 12 regions. In order to gain more visibility on how long it's taking Prism to perform the initial crawl of all resources in all regions, we have set up log shipping to central ELK (#90) and added helpful markers so that we can analyse the data returned easily (#91).
The logging added thus far is helpful, but it doesn't tell us how long Prism is taking from application start to the healthcheck …
> Logs time taken between application start and healthcheck passing successfully for each resource

- app/agent/collector.scala
- app/agent/model.scala
- app/agent/origin.scala
- app/collectors/acmCertificates.scala
- app/collectors/bucket.scala
- app/collectors/data.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/collectors/launchConfigurations.scala
- app/collectors/loadBalancers.scala
- app/collectors/reservation.scala
- app/collectors/securityGroup.scala
- app/collectors/serverCertificates.scala
- app/collectors/zone.scala
- app/conf/AWS.scala
- app/conf/context.scala
- app/controllers/Api.scala
- app/controllers/ApiResult.scala
- app/controllers/OwnerApi.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- app/utils/Marker.scala
- build.sbt
- test/ApiSpec.scala
- test/conf/PrismConfigurationSpec.scala
Currently, it is not easy for us to find out if an Amazon resource has been created in a region outside of the Guardian's preferred regions. This is a particular problem for Infosec who get asked questions like,
> "Given an ELB CNAME, can I determine if the resource is in one of our AWS organisation accounts, and if so which account?"
As well as this, we can't rule out if we've been compromised by a hostile third party if we do not have visibility over our resources in all regions. Up until now, Kate sometimes uses Cloudmapper to collect data from AWS accounts but it's not a great experience to run locally: https://github.com/duo-labs/cloudmapper
After speaking to @katebee, we received the following requirements for this work:
1. crawl all regions for AWS assets once a day, or even once …
> Crawl all regions

- app/AppLoader.scala
- app/conf/LogConfiguration.scala
Here we add the instance id and build id to prism logs, to aid developer debugging on the project.
> Adds instance and build ids to the logs

- app/AppLoader.scala
- app/agent/origin.scala
- app/collectors/lambda.scala
- app/conf/AWS.scala
- app/conf/context.scala
- app/utils/AWSCredentialProviders.scala
- build.sbt
We've moved the Lambda Collector to v2 of the AWS SDK. We've done this to aid prism in crawling all regions (PR #88). Our hypothesis is that if we can move prism onto v2 of the SDK, eventually moving to use of the asynchronous clients, we can speed up Prism's time to pass its healthcheck.
We tested this by deploying to CODE and checking that prism is crawling lambdas and completing its lambda healthcheck successfully.
> lambda moved onto aws v2

- app/collectors/acmCertificates.scala
- build.sbt
This change has been tested: `diff -I href <(jq -S '.data | .["acm-certificates"] | sort_by(.arn)' pAcm.json) <(jq -S '.data | .["acm-certificates"] | sort_by(.arn)' cAcm.json)`
> ACM Certificate Collector to AWS SDK v2

- app/collectors/bucket.scala
- build.sbt
1. After deploy, check the logs to see if we're crawling buckets at all. If not, then debug what `Region.toString` vs `GetBucketLocationResponse.locationConstraintAsString()` is in `Bucket.scala:53`, as this could be the culprit.
1. Redo teamcity build after committing change within github ui
> Bucket Collector to AWS SDK v2

- app/collectors/launchConfigurations.scala
- build.sbt
> launchConfig Collector to AWS SDK v2

- app/collectors/loadBalancers.scala
- build.sbt
> ELB Collector to AWS SDK v2

- app/jsonimplicits/implicits.scala
As part of the AWS SDK v2 upgrade, we changed a number of time types from Java Datetime to Java Instant. This broke Amiable, which was expecting milliseconds. This PR adds those milliseconds back by adding our own JSON writer. We've done this in the case that other Guardian applications may be expecting this.
We've already put out a fix for Amiable, but we can double check that Amiable still's working. We can also go through the different prism endpoints and check that the time values are all formatted as expected.
> Adds explicit JSON writer for Java Time Instant

- app/agent/model.scala
- app/controllers/Api.scala
- app/jsonimplicits/implicits.scala
- conf/routes
Introduces a new endpoint to list aws accounts containing instances indexed by prism. The output looks like this: 
This is currently on CODE https://prism.code.dev-gutools.co.uk/sources/accounts
We can use this endpoint to e.g. power UI elements that need a list of AWS accounts. It should also be useful for quickly answering the question "what account is 12312312"?
> Add /sources/accounts endpoint.

- app/agent/origin.scala
- app/collectors/serverCertificates.scala
- app/collectors/zone.scala
- build.sbt
> Route 53 Collector to AWS SDK v2

- app/collectors/serverCertificates.scala
- build.sbt
> Server Certificate Collector to AWS SDK v2

- app/agent/model.scala
- app/agent/origin.scala
- app/collectors/acmCertificates.scala
- app/collectors/bucket.scala
- app/collectors/data.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/collectors/launchConfigurations.scala
- app/collectors/loadBalancers.scala
- app/collectors/reservation.scala
- app/collectors/securityGroup.scala
- app/collectors/serverCertificates.scala
- app/collectors/zone.scala
- app/conf/context.scala
- build.sbt
The AWS SDK 2 introduces the idea of a global region for certain services. For example, Route 53 (Amazon's DNS service). Here, we add this concept to Prism's collectors which can now be Global or Regional. This change means that we can complete the migration process to sdk 2. 
No more error messages when we deploy PRs #105 and #103.
> Adds global vs regional concept to collectors

- app/collectors/bucket.scala
- we want Prism to crawl more regions (other than the current eu-west-1 and us-east-1) so that we have more visibility over our aws infrastructure. This is important for security reasons. (See more here: PR #88)
- it's hard for Prism to crawl all the aws regions (it's a lot of requests to make to AWS, which takes a long time, which means that prism is failing to pass its healthcheck), so we decided to minimise the number of regions for prism to crawl. We're doing this by shutting down regions that Guardian accounts are able to create new services in (eg https://github.com/guardian/service-control-policies/pull/3) 
-  **The problem is that we have lots of S3 buckets across many different regions** (see the results of a crawl done in November of [all aws …
> makes s3 collector global

- app/agent/collector.scala
- app/agent/model.scala
- test/CollectorModelSpec.scala
The `/sources` endpoint in Prism returns metadata about all of the active collectors. This comes from a combination of configuration read at startup and status data from the individual collectors held in application memory. Unlike a normal collector, it can by definition never be stale. Unfortunately the way that staleness is calculated means that this was stale under some configurations.
This PR modifies the `CrawlRate` object so that the `shelfLife` and `refreshPeriod` fields are `Duration` rather than `FiniteDuration`. This allows them to be set to Duration.Inf and Duration.Undefined in the case of `source` where it cannot become stale and doesn't refresh. 
Note that:
- If a normal collector is somehow configured with a refresh period that isn't finite we now log a warning and don't …
> Make the shelf life for the source agent infinite

- app/collectors/vpc.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- conf/routes
Here we add a VPC endpoint to Prism.
> We have a lot of VPC's at the guardian. These are typically created in two ways:
> - default VPC: comes with the AWS account - generally not recommended!
> - custom VPC: someone has thought about these and had to decide how the subnets in the VPC are split up. Still possibly a suboptimal setup.
> 
> VPCs have a block of IP addresses allocated to them. If set up correctly this will be a block registered with the networking team at the guardian so that one VPC doesn't share IP addresses with another.
> 
> It would be helpful to find out what the current state of play is with all VPCs - which ones are default, and what the IP ranges of each one is. At the same time it makes sense to check the layout of the VPC -e.g. is it the 'preferred' 3 private …
> Add VPCs to Prism

- app/data/Owners.scala
@pvighi was kind enough [to point out](https://groups.google.com/a/guardian.co.uk/g/ophan.dev/c/JnhcX9AcFCY/m/8CMNUqHuAQAJ) that ophan.dev@theguardian.com wasn't getting _'Instances using out of date AMIs'_ messages (presumably sent by [Amiable](https://amiable.gutools.co.uk/instanceAMIs?stack=ophan)?) about our AMIs, because the ownership field here was still against data.technology@theguardian.com - fixing that!
> Ophan Dev team owns stack tagged 'ophan'

- .github/dependabot.yml
Adds dependabot configuration for the cdk directory to keep things up to date. This is copied from the deploy-tools-platform repo.
> chore: add dependabot for cdk directory

- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
- cdk/package.json
- cdk/yarn.lock
Bumps the version of @guardian/cdk being used and aws-cdk libraries to match those being used in @guardian/cdk.
An alternative to https://github.com/guardian/prism/pull/129 and https://github.com/guardian/prism/pull/128.
> chore(deps): update @guardian/cdk to 0.37.0

- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
- cdk/package.json
- cdk/yarn.lock
Updates Prism to use `@guardian/cdk` [version 0.38.0](https://github.com/guardian/cdk/releases/tag/v0.38.0). I've commented on the diff below to explain the most significant changes in more detail.
I've tested this by deploying the change to `CODE` and confirming that Prism remained accessible throughout the deployment.
* Prism should continue to operate normally during and after the upgrade.
* We're updating security groups and that always feels a bit risky! I think that the testing done mitigates this risk sufficiently though.
> Upgrade to version 0.38.0 of @guardian/cdk

- riff-raff.yaml
Switches prism to using an ARM64 amigo recipe. 
I've tested on CODE and things seem ok. To deploy this to PROD:
- Update instance type manually of prism-PROD via cloudformation
- Merge this change
- Wait for continuous deployment to kick in 
- Test prism.gutools.co.uk
> Migrate to ARM64

- build.sbt
- riff-raff.yaml
Under ARM64 we are seeing performance issues linked to the Java 8 runtime not having been optimised for the new architecture. This PR migrates prism to Java 11 which does have optimisations for ARM64.
Note that we commonly use a number of command line options that have been removed or deprecated in Java 11.
Does prism still work after deploy? Are the GC logs still there?
Might be worth looking at average CPU usage before and after deployment.
* This might be unreliable as we've not really used Java 11 anywhere. 
* We've translated JVM parameters from 8 to 11, the translation might be wrong.
* There is a new AMIgo role which might have errors.
That said Java 11 is widely used and we are still compiling under JDK8 so this should be low risk.
> Migrate to Java 11 runtime

- app/agent/model.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/controllers/Api.scala
- conf/routes
1. Adds a new `/apps-with-cdk-version` route, so that we can track adoption/upgrade status of https://github.com/guardian/cdk across our estate
2. Updates the `/apps` response so that lambda-based apps are also included (this was previously reporting EC2-based apps only, which I think is a bug/oversight)
3. Adds `app` information to `/lambdas` response (where relevant)
4. Adds `guCdkVersion` information to `/instances` and `/lambdas` responses (where relevant)
In order to support 1, I considered an alternative implementation based on querying all stacks via the CloudFormation API. I decided not to pursue this as it would have required new IAM permissions and scraping of additional AWS data. It would also likely have been harder/slower to implement than the implementation proposed in this …
> Add new route for monitoring cdk usage

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism-access.test.ts
- cdk/lib/prism-access.ts
- cdk/lib/prism.test.ts
- cdk/lib/prism.ts
- cdk/package.json
- cdk/yarn.lock
- riff-raff.yaml
Updates to [@guardian/cdk v8.2.0](https://github.com/guardian/cdk/releases/tag/v8.2.0) 🎉 . This has got a number of breaking changes (full diff [here](https://github.com/guardian/cdk/compare/v0.38.0...v8.2.0)).
We'd need to manually apply the CFN template as the following parameters have been renamed (hopefully for the last time!):
- AMI -> AMIPrism
- InstanceType -> InstanceTypePrism
n/a
Keeping up to date.
n/a
n/a
> chore(deps): upgrade @guardian/cdk to latest (8.2.0)

- cdk/.gitignore
- cdk/jest.config.js
- cdk/jest.setup.js
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
It is currently impossible to use Dependabot to update `@guardian/cdk`.
Dependabot will raise a PR to update the version of `@guardian/cdk` in `package.json` and nothing else.
This PR will always fail CI as the value of the `gu:cdk:version` tag in our snapshots is tied to the version of `@guardian/cdk` being used.
That is, if Dependabot raises a PR to move from v1 to v2, as the snaphots are not updated at the same time, the tests fail.
In this change, we use the newly published mock in `@guardian/cdk` which results in the value of `gu:cdk:version` in the snapshots being static and thus Dependabot PRs become usable and we update `@guardian/cdk` more frequently.
I've followed the steps listed [here](https://github.com/guardian/cdk/blob/ef9f9aca26ca7aae071a9606850b56962d39dc06/docs/001-genera …
> refactor: Use `@guardian/cdk` mock to ease version upgrades

- app/collectors/lambda.scala
- build.sbt
Makes two changes to improve the lambda collection:
1. Improve handling of `null` lambda runtimes
2. Expose lambda package type
The runtime for a lambda is optional and will be `null` when the lambda is running a container.
We're seeing this `null` cause issues when filtering via regex, for example `/lambdas?runtime~=nodejs.*`.
<details>
<summary>Stack trace caused by regex filtering of runtime with `null`s</summary>
```
"java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)",
"java.base/java.util.regex.Matcher.reset(Matcher.java:416)",
"java.base/java.util.regex.Matcher.<init>(Matcher.java:253)",
"java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)",
"scala.util.matching.Regex.unapplySeq(Regex.scala:283)",
"utils.RegExMatchable.isMatch(filter.scala:14)", …
```
> fix: Make lambda runtime easier to use

- .github/dependabot.yml
The CDK project in this repository doesn't run in a PROD environment, only CI, so we can afford to use old versions of libraries for a short time. Update Dependabot's configuration to run monthly to reduce the frequency of PRs by a quarter and thus require less commitment from the team.
> chore: Run Dependabot monthly

- app/collectors/vpc.scala
There are some fields for VPCs that would be useful to have to discover if a VPC is the default one or not and also to determine if a VPC is in use.
This adds those and also changes the ARN to use the owner account number instead of the account name that it is being crawled from.
> Add VPC and subnet fields missing from Prism model

- app/collectors/cloudformationStacks.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- build.sbt
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/prism-access.ts
- conf/routes
There is a rich seam of information in the cloudformation stacks. This extracts it every few minutes and makes it available to prism clients. With this we can more easily ask questions about resources that are or are not looked after by cloudformation and identify the stack that a resource belonds to more quickly.
This should be tested in CODE to check that is works as expected and doesn't reveal private data.
- Being able to identify all S3 buckets not created in Cloudformation.
- Being able to identify any CFN stacks that have stack policies
There are a few risks worth a little more thinking about:
- will the extra data make prism too slow again?
- is any of the data in outputs and parameters for stacks be private?
> Crawl cloudformation stacks and resources

- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
We have recently had [problems](https://riffraff.gutools.co.uk/deployment/history?projectName=tools%3A%3Aprism&stage=PROD&status=Failed&pageSize=20&page=1) bringing new Prism instances into service. The [logs](https://logs.gutools.co.uk/s/devx/goto/b444cf52cb2ea71554007b3d7ce34d9c) from an instance which failed to launch this morning show Prism's initial data collection (which seems to be required for healthchecks to pass) taking longer than the current grace period of 500 seconds.
Consequently, this PR increases the ASG's [health check grace period](https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html), in an attempt to bring new instances into service more reliably. 
I have confirmed that the CFN update doesn't cause any problems/replacements by deploying to `CODE`. …
> Extend ASG healthcheck grace period

- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
This is a more generous version of https://github.com/guardian/prism/pull/226, as 600 seconds still doesn't seem to be sufficient! This [dashboard](https://logs.gutools.co.uk/s/devx/goto/62844fe86e35160bcb41ebcfa1ebd44a) suggests that 800 seconds should be OK.
> Increase ASG healthcheck grace period (again)

- app/controllers/Prism.scala
https://github.com/guardian/prism/pull/197 added new functionality for crawling CloudFormation stacks and resources.
Unfortunately, we are regularly seeing rate limiting from AWS related to this functionality and this has made `PROD` deployment extremely unreliable. If I understand correctly, AWS request quotas are implemented at the account-level, which means that this rate limiting may also interfere with other functionality which relies on this quota (e.g. Riff-Raff's CFN deployment type).
I have experimented with a change which reduces the number of calls made to AWS (by dropping the policy information), but unfortunately this is still not sufficient to avoid the rate limiting. 
Consequently, this PR disables the CFN crawling in an attempt to stabilise things again. Obviously we will …
> Disable CFN crawling

- cdk/jest.setup.js
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism-access.test.ts
- cdk/lib/prism.ts
- cdk/package.json
- cdk/yarn.lock
This PR bumps the `@guardian/cdk` to [v19.0.0](https://github.com/guardian/cdk/releases/tag/v19.0.0), allowing us to eventually make use of the [v18.1.0's new pattern tag](https://github.com/guardian/cdk/pull/603).
Once we migrate to the GuEc2App pattern, this will allow us to get the first piece of data of pattern usage into AWS, allowing us to build a lambda to query this data and offload it to CloudWatch and later Grafana.
I've manually applied this CFN update in `CODE` and confirmed that it doesn't cause any problems.
Prism's ASG is tagged with what pattern uses it.
> feat(cdk): bump @guardian/cdk to v19

- cdk/lib/prism-access.ts
- cdk/lib/prism.ts
- cdk/package.json
- cdk/yarn.lock
Upgrades to use @guardian/cdk to v19.2.1. We are already on v19.0.0, so the changes here are minimal. The primary motivation for this is to pick up https://github.com/guardian/cdk/pull/609, which is required for the migration to the EC2 App Pattern.
The snapshot tests show that the generated template is unchanged. This should be sufficient.
We will need to make fewer changes in the EC2 App Pattern migration PR(s).
This seems very low risk to me.
> Upgrade @guardian/cdk to v19.2.1

- README.md
Adds buckets to the list of things Prism knows about. Perhaps we could also add paths for the various resources?
> Add buckets to the list of things Prism knows about

- cdk/package.json
- cdk/yarn.lock
Updates to `@guardian/cdk` version 21.0.0. We also upgrade `aws-cdk` dependencies to version 1.110.1, in order to [keep up with `@guardian/cdk`](https://github.com/guardian/cdk/pull/644).
This change pulls in internal load balancer support for the EC2 app pattern (added in https://github.com/guardian/cdk/releases/tag/v19.4.0), which is needed for Prism's migration. I'm performing this upgrade in its own PR to keep the migration PR(s) as small and simple as possible.
The snapshot tests still pass, which shows that Prism's infrastructure is not changed* by this upgrade.
*except for cdk version tags!
Prism should continue working normally; there should be no noticeable changes.
As the generated CFN is not changing, this should be low risk.
> Update to cdk version 21.0.0

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/lib/prism-ec2-app.test.ts
- cdk/lib/prism-ec2-app.ts
This PR creates a new CloudFormation stack*, which defines Prism's infrastructure using our `cdk` pattern. This PR does not alter (or tear down) the current stack, as this must happen via a multi-stage process. At the end of the process, the most significant change to the underlying infrastructure will be our usage of an ALB instead of an ELB.
In this PR we are creating a new load balancer that will run in parallel to the current one. This will allow us to perform a zero-downtime migration via a three step dance:
1. Run two load balancers
1. Update the CNAME to point to the new load balancer
1. Remove the old load balancer
Riff-Raff will not be capable of deploying the stack created via this PR (it must be CloudFormed manually). A subsequent PR …
> Generate a separate stack for Prism (using cdk pattern)

- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/lib/prism-ec2-app.ts
Now that we are using the `GuPlayApp` pattern (https://github.com/guardian/prism/pull/245), we can easily add an alarm to detect cycling instances. This addresses one of the retro actions described [here](https://docs.google.com/document/d/11QMKU1J9C4aZR6cse_cE6vI1f_IKr0mLuALuwMpfJ3M/edit#heading=h.ofhrsl2zekxj). 
I've deployed this to `CODE`. The alarm configuration itself was tested as part of https://github.com/guardian/cdk/pull/594.
We will be notified if Prism instances are frequently becoming unhealthy.
We should keep an eye on this alarm and tune or remove it if it generates too much noise.
> Add an alarm to detect cycling instances

- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/lib/prism-ec2-app.ts
We extended the ASG healthcheck grace period in https://github.com/guardian/prism/pull/226 and https://github.com/guardian/prism/pull/227, as we believed this may help the healthchecks to pass. We have since reverted the feature (https://github.com/guardian/prism/pull/228) which was causing problems with the healthchecks. 
We ascertained that the problem was caused by API rate limiting (rather than increased startup time). Consequently, this PR reinstates the grace period that was in place before that experimentation began.
> Reduce ASG healthcheck grace period

- README.md
This PR removes an erroneous bracket that was causing the Buckets link to render incorrectly
> Fix Buckets README link markdown

- project/plugins.sbt
This brings improved branch name detection when using GitHub Actions for CI.
See https://github.com/guardian/sbt-riffraff-artifact/pull/64.
> chore: Bump `sbt-riffraff-artifact` to v1.1.17

- .github/workflows/ci.yml
I messed up v1.0.1 😅 .
https://github.com/guardian/actions-assume-aws-role/releases
> chore: Bump `guardian/actions-assume-aws-role` to v1.0.2

- app/views/index.scala.html
- build.sbt
- project/build.properties
- project/plugins.sbt
This PR updates `sbt` to version `1.5.6`. 
This version of `sbt` was incompatible with Play `2.8.2`, so I have also bumped the Play version to `2.8.8` and made a few small changes to keep things working.
I've confirmed that this change can be [successfully deployed to `CODE`](https://riffraff.gutools.co.uk/deployment/view/10f12972-ca84-4d67-acff-ce9aa50caba7).
* All functionality should work as before
* The `sbt` [version](https://github.com/sbt/sbt/releases/tag/v1.5.6) is no longer vulnerable to [Remote code injection in Log4j](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)
This should be pretty low risk due to testing described above.
> Update to sbt version 1.5.6 and Play version 2.8.8

- .github/workflows/ci.yml
We developed https://github.com/guardian/actions-assume-aws-role to support the migration to GitHub Actions (more specifically, it allowed us to upload build artifacts to Riff-Raff's S3 buckets without using permanent credentials).
There is now an official action (maintained by AWS) which offers this functionality - https://github.com/aws-actions/configure-aws-credentials. This PR switches to using the AWS alternative instead of the (now deprecated) Guardian action. 
Related PRs:
https://github.com/guardian/actions-assume-aws-role/pull/80
https://github.com/guardian/node-riffraff-artifact/pull/33
https://github.com/guardian/sbt-riffraff-artifact/pull/69
> Use aws-actions/configure-aws-credentials instead of guardian/actions-assume-aws-role

- app/agent/model.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/controllers/Api.scala
This PR adds some more metadata to the `/apps-with-cdk-version` endpoint. This endpoint supplies the data for our [GuCDK adoption dashboard](https://metrics.gutools.co.uk/d/AysWSbQMk/devx-guardian-cdk-adoption?orgId=1), so adding this metadata will help us to surface more useful information. For example, this allows us to more easily answer questions likee:
* How many EC2 vs Lambda based apps are left to migrate? 
* Which teams own the EC2-based services that still need to be migrated to GuCDK?
I've deployed this to `CODE` and confirmed that the new data is coming through as expected.
> Add more metadata to /apps-with-cdk-version

- app/data/Owners.scala
It's currently hard to differentiate between apps that DevX own and apps that are assigned to DevX due to a lack of owner; this [technique](https://support.google.com/a/users/answer/9308648?hl=en) should make it easier.
> Use task-specific email address for infrastructure without an owner

- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
This PR upgrades `@guardian/cdk` in order to pick up automatic log shipping (https://github.com/guardian/cdk/pull/1211). This feature also relies on [an AMIgo role](https://amigo.gutools.co.uk/roles#cdk-base), but [the recipe used for baking our AMI already includes this role](https://amigo.gutools.co.uk/recipes/arm64-bionic-java11-deploy-infrastructure), so this PR is the only change required to get this working 🎉 
I've [deployed this to `CODE`](https://riffraff.gutools.co.uk/deployment/view/cc355a99-b93c-4c0d-84e8-663a5baa9995) and confirmed that [logs show up as expected](https://logs.gutools.co.uk/s/devx/goto/97d6c700-c098-11ec-9ca6-0778ed297cab).
Prism's `cloud-init-output.log` is available in ELK.
I think this is a pretty low risk change.
> Upgrade @guardian/cdk to enable cloud-init-output log shipping

- cdk/package.json
- cdk/yarn.lock
This PR is a follow-up in response to https://github.com/guardian/prism/pull/318#discussion_r854004373; the snapshot tests indicate that there are no infrastructure changes introduced by this upgrade.
> Use official release of @guardian/cdk

- .gitignore
- app/conf/context.scala
- app/controllers/Prism.scala
This collector was introduced [here](https://github.com/guardian/prism/pull/197).
But [quickly disabled](https://github.com/guardian/prism/pull/228) as it was hitting rate limits.
The feature would be useful for some CDK tracking we are doing andI wonder if using the 'slow' (once per day) crawl rate will help here.
> Re-enable cloudformation crawling

- app/collectors/cloudformationStacks.scala
- app/jsonimplicits/implicits.scala
*Follows: https://github.com/guardian/prism/pull/334.*
This is of interest for CDK tracking, as we plan to do this via template metadata. As part of this, I've removed some stuff to simplify and make sure this is an API-request-net-neutral™℠®© change.
Note, we should wait to see if the previous PR solves the rate limiting issue. Failing that, we may have to explore some kind of (exponential) back-off strategy to better handle the limits here.
> Include Cloudformation template metadata

- app/data/Owners.scala
The consent team isn't represented in owners so is missing from downstream reporting. This change adds the consent team & ownership of stacks:
- [Baton](https://github.com/guardian/baton/blob/main/cdk/baton-stack.ts#L53)
- [CMP Monitoring](https://github.com/guardian/consent-management-platform/pull/654): PR needs merging!
Project compiles, tests pass, consent is visible as an owner in the Prism API.
> Add consent as owner

- .gitignore
- marauder/Gemfile.lock
Adds a lock file for marauder's dependencies because that's best practice, and without one, Snyk will require installation of gems at runtime to check for vulnerabilities. The caveat is that I am not versed in the ruby ecosystem, so feel free to point out any missteps.
I don't actually know how to test this works as expected...
> Add Gemfile.lock for marauder dependencies

- app/collectors/vpc.scala
- project/build.properties
- riff-raff.yaml
A subnet is considered private unless it has an internet gateway associated to its route table.
This is helpful for us to better understand the shape of VPCs across the dept - particularly the number of VPCs that do not have any private subnets.
> Add subnet scope to VPC reports

- app/agent/origin.scala
Use getCallerIdentity instead of getUser to enable better results while running locally (because of a permission problem).
Co-authored-by Akash and Nic
Switching form getUser to getCallerIdentity will ensure accountNumber will show when running locally because of an permission problem with aws credentials preventing this
http://localhost:9000/sources/accounts
Should not return ???????? for accountNumber any more
Any side effects would only result in problems within devX, so we feel we can go ahead.
> Use getCallerIdentity instead of getUser

- app/controllers/Api.scala
Fix for misleading entry gu, when querying sources/accounts. This will not show any more.
Co-authored-by Akash and Nic
Only entries of type AmazonOrigin will be used to build json result for the query sources/accounts
https://prism.gutools.co.uk/sources/accounts
should not yield
accountName "gu"
any more
Any side effects would only result in problems within devX, so we feel we can go ahead.
> Fix for misleading entry gu, when querying sources/accounts

- app/AppComponents.scala
- app/RequestLoggingFilter.scala
A variant of https://github.com/guardian/prism/pull/292.
It will be useful to know how Prism is accessed. In this change, we add a filter to log each request. The log lines have some markers, so we can interrogate them more easily in Central ELK.
- Deploy to CODE
- Interact with Prism CODE
- View [logs in Central ELK](https://logs.gutools.co.uk/s/devx/goto/29072010-4bb5-11ed-a02a-2d44512a4a41)
We know which endpoints are in use.
N/A
> feat: Add a request logger

- build.sbt
This follows out own advice and upgrade to 2.13.10 to avoid the vulnerability:
https://www.cve.org/CVERecord?id=CVE-2022-36944
> Upgrade Scala version to 2.13.10

- riff-raff.yaml
It is preferable to omit the bucket from riff-raff.yml if the AWS account deployed from has the necessary SSM parameters specifying the dist bucket location.
In this case the Baton AWS account has the SSM parameter `/account/services/artifact.bucket` set to `deploy-tools-dist` so the explicit config is unnecessary.
Note: this change is also used to check a riff-raff change in https://github.com/guardian/riff-raff/pull/885 to allow ommision of `bucketSsmLookup` to reduce verbosity.
> Remove explicit bucket from riff-raff.yml

- app/data/Owners.scala
DevX are currently receiving emails about out of date AMIs in the `editorial-feeds` stack; this is happening because the stack has no owner in Prism. This PR adds the necessary config to send these warnings to the correct team.
> Add an owner for editorial-feeds stack

- app/collectors/bucket.scala
We've encountered a bucket where the policy is set to deny `s3:*` if the request does not originate from a specific IP address.
Whilst this scenario is quite rare, we should handle it so that the healthcheck can pass.
Log at warn level for visibility.
Easiest would be to [deploy `main` to CODE](https://riffraff.gutools.co.uk/deployment/history?projectName=devx%3A%3Aprism&page=1), observe a failing deploy, then [deploy this branch to CODE](https://riffraff.gutools.co.uk/deployment/view/f64d8c6d-35c1-40f9-be26-c844c4cc768d) and observe a successful deploy.
[Prism's healthcheck](https://github.com/guardian/prism/blob/00756c0f36192fcbe34ec30c42dc0186d921b0b0/app/controllers/Api.scala#L131-L150) is such that it'll only pass if it is able to crawl every resource. The healthcheck on `main` is …
> fix(s3): Handle case where we don't have access to a bucket

- build.sbt
Update AWS SDKs to their latest version to resolve a high vulnerability reported by Snyk.
In theory, yes. However according to [their FAQs](https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md):
> Scala Steward first proposes an update to the latest patch version at the same minor and major version. If the dependency is already on the latest patch version, it proposes an update to the latest minor version at the same major version.
> – https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md
That is, for the v2 SDK, Scala Steward would only move to the next minor version once we are on the latest patch version. Given the AWS SDK sometimes sees multiple patch versions a day, it's unlikely we'll meet this requirement. Doing it manually is simpler.
> chore(deps): Use the latest versions of AWS SDKs for Java

- app/RequestLoggingFilter.scala
- app/agent/collector.scala
- app/controllers/Prism.scala
- app/pekko/gu/agent/Agent.scala
- app/utils/ScheduledAgent.scala
- conf/application.conf
- project/plugins.sbt
The dependency PR upgrading to play 3.0.0 fails because you have to migrate akka to pekko manually
[Doc Migration to play 3.0. akka to pekko](https://medium.com/xworks-techinsights/akka-to-pekko-migration-step-by-step-cca64bc61016)
Upgrade to play 3.0.0
Deployed to and checked on code (https://prism.code.dev-gutools.co.uk/)
> Upgrade to play 3.0.0

- build.sbt
Exclude transitive dependencies to the old artifacts
Ashleigh pointed to me to an
[issue in the play-json-extensions](https://github.com/bizzabo/play-json-extensions/issues/94)
I added the excludeDependencies suggested, but am not 100% sure if this is needed since
sbt dependencyTree | grep ':play_'
[info]   | | +-org.playframework:play_2.13:3.0.0 [S]
[info]   | +-org.playframework:play_2.13:3.0.0 [S]
[info]   | +-org.playframework:play_2.13:3.0.0 [S]
[info]   | | +-org.playframework:play_2.13:3.0.0 [S]
[info]   | +-org.playframework:play_2.13:3.0.0 [S]
stays the same.
org.playframework:play_2.13:3.0.0, represents a certain version of the Play Framework.
The play_2.13 part denotes that this version of the Play Framework has been compiled with Scala 2.13.
The 3.0.0 part stands for the …
> As of Play 3.0, groupId has changed to org.playframework;

- app/data/Owners.scala
Add the owners of the `ai` and `data-science` stacks so that AMIable can route messages correctly.
If an owner cannot be found, the alert gets sent to DevX as a fallback address, as seen in the image below:
> fix(owners): Add owners for `ai` and `data-science` stacks

- app/data/Owners.scala
I've just seen this listing linked in chat this morning, and we're not signed up for notifications from our stack. This PR fixes that
> Add newsroom res as owners of print prod stack

- .github/workflows/ci.yml
- build.sbt
- project/plugins.sbt
- scripts/ci
The SBT plugin [sbt-riffraff-artifact](https://github.com/guardian/sbt-riffraff-artifact) is deprecated. This change adopts [guardian/actions-riff-raff](https://github.com/guardian/actions-riff-raff) in its place.
[Deploy to CODE](https://riffraff.gutools.co.uk/deployment/view/11388307-b992-4441-9a89-735f45959931), and observe it succeed. Also observe the build info at the [bottom](https://github.com/guardian/prism/blob/d417371a06924c323683e6157e7582fce9abdaf8/app/views/index.scala.html#L69-L72) of https://prism.code.dev-gutools.co.uk/ matching the deployed build.
> ci: Adopt `guardian/actions-riff-raff`

- app/jsonimplicits/implicits.scala
- build.sbt
- project/plugins.sbt
Drops the `play-json-extensions` dependency. This dependency was used to auto-generate JSON Writer implementations for case classes with more than 22 fields.
Unfortunately it appears this dependency hasn't been updated in a long time and [doesn't fully support Play 3 yet](https://github.com/bizzabo/play-json-extensions/issues/94) causing us to have to do some trickery with dependencies to avoid loading in any Play 2 dependencies, specifically Akka.
Thankfully we only had 1 class that was using this extension which was quite easy to write a custom JSON Writer implementation for.
> Drop `play-json-extensions` dependency

- cdk/package-lock.json
- cdk/package.json
- package-lock.json
bumps `@guardian/eslint-config-typescript`
for some reason #887 didn't like it
> bump `@guardian/eslint-config-typescript`

- cdk/bin/cdk.ts
- cdk/lib/prism-access.test.ts
- cdk/lib/prism-access.ts
- cdk/lib/prism-ec2-app.test.ts
- cdk/lib/prism-ec2-app.ts
- cdk/package-lock.json
- cdk/package.json
Configure `eslint` to fail on `prettier` errors. This ensures a consistent style for quote marks, indent levels, etc. It also means the project uses the departmental code style.
This is a no-op, as demonstrated by the CDK snapshot remaining unchanged.
> chore(lint): Fail on `prettier` errors

- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
Deployments are currently flaky with the health check failing every so often due to rate limiting from AWS.
This screenshot shows build 1386 failing and succeeding to deploy:
Increase the health check grace period as a temporary solution to hopefully increase the determinism of deployments.
> fix: Increase health check to 15 minutes

- .github/workflows/ci.yml
- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.test.ts
- cdk/lib/prism.ts
- scripts/ci
Uses the new `GuEc2AppExperimental` available in [GuCDK v59.5.0](https://github.com/guardian/cdk/releases/tag/v59.5.0) to deploy changes to the autoscaling group entirely via a CloudFormation update.
Deploy the branch?! It should succeed. This has been [done on CODE](https://riffraff.gutools.co.uk/deployment/view/2d014f20-ed9b-4164-b986-dc017e90dc34).
More data points to evaluate the effectiveness of `GuEc2AppExperimental`.
> feat: Perform EC2 deployments via CloudFormation

- .github/dependabot.yml
Configure Dependabot to run monthly for:
- PRs less often
- Alignment with our other repositories
> chore(dependabot): Run monthly

- build.sbt
The V1 AWS autoscaling SDK library is [not used](https://github.com/guardian/prism/pull/112/files#r542428273). It was added in https://github.com/guardian/prism/pull/28. Since https://github.com/guardian/prism/pull/112 we've been using the V2 SDK.
CI passing should suffice here. I have successfully [deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/47b98407-f819-4467-8720-c8aabd08a325) too.
> chore(deps): Remove `com.amazonaws.aws-java-sdk-autoscaling`
