guardian/prism

- app/collectors/serverCertificates.scala
- app/controllers/Api.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- conf/routes
Add a collector that crawls all server certificates stored in IAM.
This will allow us to build tooling to check for expiring certificates.
> Index server certificates

- build.sbt
- project/plugins.sbt
- riff-raff.yaml
Supercedes #34 now there is a release of the plugin.
Remove the cloudformation deployment (this should move to the deploy-tools-platform repo).
> Update sbt riff-raff plugin and switch to riff-raff.yaml file

- app/controllers/OwnerApi.scala
- app/data/Owners.scala
- app/jsonimplicits/implicits.scala
- app/model/Owner.scala
- app/model/SSA.scala
- conf/routes
- test/OwnerApiSpec.scala
- test/data/OwnersSpec.scala
This PR is adding the concept of owners into Prism.
Each owner owns a list of SSA (stack, stage, app)
This patch is adding 3 /endpoints:
GET /owners
```
"status": "success",
"lastUpdated": "2017-03-29T15:07:13.815+01:00",
"stale": false,
"staleSources": [
],
"data": {
"owners": [
{
"id": "adam.fisher",
"stacks": [
{
"stack": "security"
}
]
},
{
"id": "dotcom.platform",
"stacks": [
{
"stack": "frontend"
}
]
},
{
"id": "simon.hildrew",
"stacks": [
{
"stack": "deploy"
}
]
},
{
"id": "phil.wills",
"stacks": [
{
}
]
}
]
},
"sources": [
{
"resource": "Owners",
"origin": {
"vendor": "prism",
"accountName": "prism"
},
"status": "success",
"createdAt": "2017-03-29T15:07:13.815+01:00",
"itemCount": 4,
"age": 0,
"stale": false
}
]
}
```
GET /owners/for-stack?stack=frontend
```
{
"status": "success", …
```
> Add Owners

- app/collectors/bucket.scala
There seems to be a discrepancy between the buckets listed by the `listBuckets` API call and those that actually exist. `listBuckets` returns buckets that have been deleted for an unknown period of time after the deletion. Later queries then fail to get further information.
This change catches those failures and makes buckets in this state disappear.
> Deal with buckets that don't exist despite being listed

- app/data/Owners.scala
So they get all the lovely emails about things
> Make identity own discussion

- app/akka/agent/Agent.scala
Since agents have been deprecated in Akka, we have included the source within the Prism directory as a quick fix rather than migrating to Actors within the [Prism play upgrade](https://github.com/guardian/prism/pull/84). This PR fixes a [comment](https://github.com/guardian/prism/pull/84#discussion_r507694146) at the end of #84 that we should, where possible, leave the Agent code unmodified and include a link to the source.
> Only apply required modifications to Agent.scala and link to source

- app/agent/collector.scala
- app/agent/model.scala
- app/agent/origin.scala
- app/collectors/acmCertificates.scala
- app/collectors/bucket.scala
- app/collectors/data.scala
- app/collectors/image.scala
- app/collectors/instance.scala
- app/collectors/lambda.scala
- app/collectors/launchConfigurations.scala
- app/collectors/loadBalancers.scala
- app/collectors/reservation.scala
- app/collectors/securityGroup.scala
- app/collectors/serverCertificates.scala
- app/collectors/zone.scala
- app/conf/AWS.scala
- app/conf/context.scala
- app/controllers/Api.scala
- app/controllers/ApiResult.scala
- app/controllers/OwnerApi.scala
- app/controllers/Prism.scala
- app/jsonimplicits/implicits.scala
- app/utils/Marker.scala
- build.sbt
- test/ApiSpec.scala
- test/conf/PrismConfigurationSpec.scala
This reimplements PR #88, but with the ami configuration fixed.
> Crawl all regions 2

- app/collectors/securityGroup.scala
- build.sbt
**This is ready to be merged to master now**
> Security Group Collector to AWS SDK v2

- app/collectors/instance.scala
> Instance Collector to AWS SDK v2

- app/collectors/reservation.scala
> Reservation Collector to AWS SDK v2

- app/collectors/image.scala
remove `account.amis` block from CODE config after testing
> Images Collector to AWS SDK v2

- app/agent/origin.scala
Prism currently showing a warning for `Source is not closed` as all sources must be closed and since the migration to scala2.13 it kindly warns you when you make this mistake. This fixes that by ensuring that it is closed before moving on.
Should be a no-op change.
No more error when compiling.
> Fix Source not being closed

- app/collectors/bucket.scala
In PR #113 we added a TODO, which @sihil confirmed can now be removed.
> remove TODO from PR#113

- build.sbt
- riff-raff.yaml
- scripts/ci
Configures CD for cloudformation template.
Deploy to CODE? (I've done this).
CD!
n/a
n/a
> build: configure CD of cloudformation

- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.ts
Implements a [suggestion](https://github.com/guardian/prism/pull/135#discussion_r582000375) that we discussed on a previous PR.
> Run a single instance in CODE

- app/collectors/lambda.scala
The healthcheck succeeds only after the first crawl of AWS has completed.
When a new runtime gets added to AWS Lambda, the AWS SDKs need to be bumped to recognise it, else it'll be [`Runtime.UNKNOWN_TO_SDK_VERSION`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/model/Runtime.html#UNKNOWN_TO_SDK_VERSION).
This PR uses the safer [`runtimeAsString`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/model/FunctionConfiguration.html#runtimeAsString--) property for the lambda runtime:
> If the service returns an enum value that is not available in the current SDK version, runtime will return Runtime.UNKNOWN_TO_SDK_VERSION. The raw value returned by the service is available from runtimeAsString().
This is safer compared to …
> fix: use safer API for lambda runtime

- app/utils/filter.scala
A small change to use more inclusive language.
See:
- https://github.com/guardian/managers-guide/blob/9caadf749c58cf8882b54e3cc9ca27327d1c5ba8/docs/guidelines/inclusive-communication.md
This should be a no-op.
> chore: Update language to be more inclusive

- README.md
Prism scans VPCs too! Also, linkify all the entities so people can jump straight in
> Add VPCS to readme entities list. Linkify urls

- project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.5.7
> Update to sbt 1.5.7

- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
Bump GuCDK to the latest version.
> chore: Bump `@guardian/cdk` to 34.0.0

- app/data/Owners.scala
Adds newsletters.dev as owners of the newsletters stack
> Add newsletters.dev as owners of the newsletters stack

- build.sbt
- cdk/bin/cdk.ts
- cdk/cdk.json
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/lib/prism-access.test.ts
- cdk/lib/prism-access.ts
- cdk/lib/prism-ec2-app.test.ts
- cdk/lib/prism-ec2-app.ts
- cdk/package.json
- cdk/yarn.lock
- riff-raff.yaml
Updates `@guardian/cdk` from 34.0.0 to 41.0.1. This is quite a big change - I've tried to annotate the snapshot changes with explanations.
> chore(deps): Update `@guardian/cdk` to v41.0.1

- .github/workflows/ci.yml
Updates CI to use latest versions of GitHub Actions, and also use Java 11 (corretto) to match that used locally and at runtime.
CI should pass and produce a deployable artifact.
> ci: Update GHA workflow with latest versions and use Java 11

- cdk/bin/cdk.ts
- cdk/cdk.json
- cdk/jest.config.js
- cdk/lib/__snapshots__/prism-access.test.ts.snap
- cdk/lib/__snapshots__/prism-ec2-app.test.ts.snap
- cdk/package.json
- cdk/yarn.lock
> **Note**
> Easiest to review [commit by commit](https://github.com/guardian/prism/pull/435/commits).
Updates various dependencies within the CDK project.
| Module                             | From     | To       |
|------------------------------------|----------|----------|
| @guardian/cdk                      | 47.3.5   | 48.4.0   |
| aws-cdk                            | 2.44.0   | 2.45.0   |
| aws-cdk-lib                        | 2.44.0   | 2.44.0   |
| constructs                         | 10.1.117 | 10.1.127 |
| jest                               | 26.6.3   | 29.3.0   |
| @types/jest                        | 27.4.1   | 29.2.2   |
| ts-jest                            | 26.5.6   | 29.0.3   |
| typescript                         | 4.6.3    | 4.8.4    |
| ts-node …
> chore(deps): Update various CDK dependencies

- .github/workflows/snyk.yml
This allows easier testing of the Snyk workflow, by enabling manual execution of the Snyk workflow.
> Allow workflow_dispatch for Snyk workflow

- app/agent/origin.scala
Prism's collectors operate in various AWS accounts.
AWS accounts are listed in two ways within configuration:
1. The name, and the IAM role to assume
<details>
<summary>Example</summary>
```json
"accounts.aws": {
"baton": {
"ownerId": "identitydev",
"role": "arn:aws:iam::000000000000:role/baton-account"
},
"deployTools": {
"ownerId": "deploy-tools",
"role": "arn:aws:iam::000000000000:role/deploy-tools-account"
},
}
```
</details>
2. The name, the IAM role to assume, and the account number
<details>
<summary>Example</summary>
```json
"accounts.amis": {
"amazon": {
"accountNumber": "137112412989",
"role": "arn:aws:iam::000000000000:role/deploy-tools-account"
},
"canonical": {
"accountNumber": "099720109477",
"role": "arn:aws:iam::000000000000:role/deploy-tools-account"
}
}
```
</details> …
> fix: Keep account number if already provided in config

- app/data/Owners.scala
Adds pfi-llama stack to anghammarad so that we get notifications when the AMIs are out of date
> Add pfi-llama stack

- app/data/Owners.scala
Reverts guardian/prism#725 - we have deleted pfi-llama
> Revert "Add pfi-llama stack"

- build.sbt
Remove unused resolvers from build.sbt
CI passing should be sufficient, as we just need to check all the required dependencies are pulled
> Remove unused custom resolvers

- cdk/bin/cdk.ts
- cdk/lib/__snapshots__/prism.test.ts.snap
- cdk/lib/prism.test.ts
- cdk/lib/prism.ts
- cdk/package-lock.json
- cdk/package.json
> [!NOTE]
> Easiest to review [commit by commit](https://github.com/guardian/prism/pull/1047/commits).
Updates GuCDK from 61.3.1 to 62.0.0. There are a number of changes being made here; I've split the significant changes into their own commits.
See updated snapshot and observe CI passing.
I've also [successfully deployed to CODE](https://riffraff.gutools.co.uk/deployment/view/0dc66495-0c78-4b12-ac0d-c7d1030d2c02).
> chore(deps-dev): Update GuCDK from 61.3.1 to 62.0.0 
